name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: cache for dependencies
      uses: actions/cache@v4
      if: matrix.os != 'windows'
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}/_deps
        key: ${{ runner.os }}-dependencies-${{ hashFiles('luauver.txt') }}
    - name: cache for dependencies
      uses: actions/cache@v4
      if: matrix.os == 'windows'
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}\_deps
        key: ${{ runner.os }}-dependencies-${{ hashFiles('luauver.txt') }}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: create timestamp
      id: timestamp
      run: echo "value=$(date +'%F_%H-%M-%S')" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v4
      if: matrix.os != 'windows'
      with:
        name: luau-${{matrix.os}}
        path: luau*
        overwrite: true
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'windows'
      with:
        name: luau-${{matrix.os}}
        path: Release\luau*.exe
        overwrite: true
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.timestamp.outputs.value }}
        release_name: ${{ steps.timestamp.outputs.value }}
        draft: true
    - name: pack
      if: matrix.os != 'windows'
      run: zip ldd-${{matrix.os}}.zip ${{ steps.strings.outputs.build-output-dir }}/ldd
    - name: pack
      if: matrix.os == 'windows'
      run: 7z a ldd-${{matrix.os}}.zip ${{ steps.strings.outputs.build-output-dir }}\ldd.exe
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ldd-${{matrix.os}}.zip
        asset_name: ldd-${{matrix.os}}.zip
        asset_content_type: application/octet-stream
